src/Marketkhoone.Web/Pages/Admin/Seller/Index.cshtml.cs
using EShopMarket.Common.Helpers;
using Ganss.Xss;
using MarketKhoone.Common.Constants;
using MarketKhoone.Common.IdentityToolkit;
using MarketKhoone.DataLayer.Context;
using MarketKhoone.Entities.Enums.Seller;
using MarketKhoone.Services.Contracts.IFacadePattern;
using MarketKhoone.ViewModels.Sellers;
using Microsoft.AspNetCore.Mvc;

namespace Marketkhoone.Web.Pages.Admin.Seller
{
    public class IndexModel : PageBase
    {
        #region Costructor

        private readonly IFacadeServices _facadeServices;
        private readonly IHtmlSanitizer _htmlSanitizer;
        private readonly IUnitOfWork _uow;

        public IndexModel(IFacadeServices facadeServices, IHtmlSanitizer htmlSanitizer, IUnitOfWork uow)
        {
            _facadeServices = facadeServices;
            _htmlSanitizer = htmlSanitizer;
            _uow = uow;
        }
        #endregion

        [BindProperty(SupportsGet = true)]
        public ShowSellersViewModel Sellers { get; set; } = new();
        public void OnGet()
        {
        }

        public async Task<IActionResult> OnGetGetDataTableAsync()
        {
            if (!ModelState.IsValid)
            {
                return Json(new JsonResultOperation(false, PublicConstantStrings.ModelStateErrorMessage)
                {
                    Data = ModelState.GetModelStateErrors()
                });
            }
            return Partial("List", await _facadeServices.SellerService.GetSellers(Sellers));
        }


        public async Task<IActionResult> OnGetGetSellerDetails(long sellerId)
        {

            var seller = await _facadeServices.SellerService.GetSellerDetails(sellerId);

            if (seller is null)
            {
                return Json(new JsonResultOperation(false, PublicConstantStrings.RecordNotFoundMessage));
            }
            return Partial("SellerDetails", seller);

        }

        public async Task<IActionResult> OnPostRejectSellerDocuments(SellerDetailsViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return Json(new JsonResultOperation(false, "لطفا دلایل رد مدارک فروشنده را وارد نمایید"));
            }

            var seller = await _facadeServices.SellerService.FindByIdAsync(model.Id);
            if (seller is null)
            {
                return Json(new JsonResultOperation(false, "فروشنده مورد نظر یافت نشد"));
            }

            seller.DocumentStatus = DocumentStatus.Rejected;
            seller.RejectReason = _htmlSanitizer.Sanitize(model.RejectReason);
            await _uow.SaveChangesAsync();
            return Json(new JsonResultOperation(true, "مدارک فروشنده مورد نظر با موفقیت رد شد"));
        }

        public async Task<IActionResult> OnPostConfirmSellerDocuments(long id)
        {
            if (id < 1)
            {
                return Json(new JsonResultOperation(false));
            }

            var seller = await _facadeServices.SellerService.FindByIdAsync(id);
            if (seller is null)
            {
                return Json(new JsonResultOperation(false, PublicConstantStrings.RecordNotFoundMessage));
            }

            seller.DocumentStatus = DocumentStatus.Confirmed;
            seller.RejectReason = null;
            await _uow.SaveChangesAsync();
            return Json(new JsonResultOperation(true, "مدارک فروشنده مورد نظر با موفقیت تایید شد"));
        }

        public async Task<IActionResult> OnPostRemoveUser(long id)
        {
            if (id < 1)
            {
                return Json(new JsonResultOperation(false));
            }

            var seller = await _facadeServices.SellerService.GetSellerToRemoveInManagingSellers(id);
            if (seller is null)
            {
                return Json(new JsonResultOperation(false, "فروشنده مورد نظر یافت نشد"));
            }
            _facadeServices.SellerService.Remove(seller);
            
            seller.User.IsSeller = false;
            //ولی مشکل اینه ، ما در اینجا به 
            //User
            //دسترسی نداریم
            //باید در سروریس این اکشن
            //.Include(x=>x.User)
            //رو اینکلود کنیم تا به یوزر دسترسی پیدا کنیم


            //await _uow.SaveChangesAsync();
            //_facadeServices.UploadedFileService.DeleteFile(seller.IdCartPicture, "images", "seller-id-cart-pictures");
            //_facadeServices.UploadedFileService.DeleteFile(seller.Logo, "images", "seller-logos");
            return Json(new JsonResultOperation(true, "فروشنده مورد نظر با موفقیت حذف شد"));
        }
    }
}

src/Marketkhoone.Web/Pages/Admin/Seller/SellerDetails.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Marketkhoone.Web.Pages.Admin.Seller
{
    public class SellerDetailsModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

src/Marketkhoone.Web/Pages/Seller/ConfirmationPhoneNumber.cshtml.cs
using EShopMarket.Common.Helpers;
using MarketKhoone.Common.Helpers;
using MarketKhoone.Common.IdentityToolkit;
using MarketKhoone.DataLayer.Context;
using MarketKhoone.Services.Contracts.Identity;
using MarketKhoone.Services.Contracts.IFacadePattern;
using MarketKhoone.ViewModels.Sellers;
using Microsoft.AspNetCore.Mvc;

namespace Marketkhoone.Web.Pages.Seller
{
    public class ConfirmationPhoneNumberModel : PageBase
    {
        #region Constructor

        private readonly IApplicationUserManager _userManager;
        private readonly IApplicationSignInManager _signInManager;
        private readonly IUnitOfWork _uow;
        private readonly IFacadeServices _facadeServices;

        public ConfirmationPhoneNumberModel(IApplicationUserManager userManager,
            IUnitOfWork uow, IFacadeServices facadeServices, IApplicationSignInManager signInManager)
        {
            _userManager = userManager;
            _uow = uow;
            _facadeServices = facadeServices;
            _signInManager = signInManager;
        }

        #endregion


        [TempData]
        public string ActivationCode { get; set; }
        [BindProperty(SupportsGet = true)]
        public ConfirmationSellerPhoneNumberViewModel Confirmation { get; set; }
            = new();

        public async Task<IActionResult> OnGetAsync(string phoneNumber)
        {
            var userSendSmsLastTime = await _userManager.GetSendSmsLastTimeAsync(phoneNumber);
            if (userSendSmsLastTime is null)
            {
                return RedirectToPage("/Error");
            }

            #region Development

            var user = await _userManager.FindByNameAsync(phoneNumber);
            var phoneNumberToken = await _userManager.GenerateChangePhoneNumberTokenAsync(user, phoneNumber);
            ActivationCode = phoneNumberToken;

            #endregion

            var (min, sec) = userSendSmsLastTime.Value.GetMinuteAndSecondForLoginWithPhoneNumberPage();
            Confirmation.SendSmsLastTimeMinute = min;
            Confirmation.SendSmsLastTimeSecond = sec;
            Confirmation.PhoneNumber = phoneNumber;
            return Page();
        }
        public async Task<IActionResult> OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Json(new JsonResultOperation(false, "مقادیر را به درستی وارد نمایید")
                {
                    Data = ModelState.GetModelStateErrors()
                });
            }

            var user = await _userManager.FindByNameAsync(Confirmation.PhoneNumber);
            if (user is null)
            {
                return Json(new JsonResultOperation(false, "شماره تلفن مورد نظر یافت نشد"));
            }

            var result = await _userManager.VerifyChangePhoneNumberTokenAsync(user, Confirmation.ActivationCode, Confirmation.PhoneNumber);
            if (!result)
            {
                return Json(new JsonResultOperation(false, "کد وارد شده صحیح نمیباشد"));
            }

            user.IsSeller = true;
            await _userManager.UpdateAsync(user);
            await _uow.SaveChangesAsync();
            return Json(new JsonResultOperation(true, "شماره تلفن شما با موفقیت تایید شد")
            {
                Data = Confirmation.PhoneNumber
            });
        }

        public async Task<IActionResult> OnPostReSendSellerSmsActivationAsync(string phoneNumber)
        {

            //System.Threading.Thread.Sleep(2000);
            var user = await _userManager.FindByNameAsync(phoneNumber);
            if (user is null)
                return Json(new JsonResultOperation(false));
            if (user.SendSmsLastTime.AddMinutes(3) > DateTime.Now)
                return Json(new JsonResultOperation(false));
            var phoneNumberToken = await _userManager.GenerateChangePhoneNumberTokenAsync(user, phoneNumber);
            // todo: Uncomment when publishing

            _facadeServices.SendSmsService.LoginCodeForUserInWebsiteOne(phoneNumber, phoneNumberToken);

            user.SendSmsLastTime = DateTime.Now;
            await _uow.SaveChangesAsync();
            return Json(new JsonResultOperation(true, "کد فعال سازی مجددا ارسال شد")
            {
                Data = new
                {
                    activationCode = phoneNumberToken
                }
            });
        }

    }
}

src/Marketkhoone.Web/Pages/Seller/CreateSeller.cshtml.cs
using AutoMapper;
using EShopMarket.Common.Helpers;
using MarketKhoone.Common;
using MarketKhoone.Common.Constants;
using MarketKhoone.Common.Helpers;
using MarketKhoone.Common.IdentityToolkit;
using MarketKhoone.DataLayer.Context;
using MarketKhoone.Services.Contracts.Identity;
using MarketKhoone.Services.Contracts.IFacadePattern;
using MarketKhoone.Services.Services.Identity;
using MarketKhoone.ViewModels;
using MarketKhoone.ViewModels.Sellers;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace Marketkhoone.Web.Pages.Seller
{
    public class CreateSellerModel : PageBase
    {
        #region Constructor

        private readonly IApplicationUserManager _userManager;
        private readonly IFacadeServices _facadeService;
        private readonly IMapper _mapper;
        private readonly IUnitOfWork _uow;

        public CreateSellerModel(IApplicationUserManager userManager,
            IFacadeServices facadeService, IMapper mapper, IUnitOfWork uow)
        {
            _userManager = userManager;
            _facadeService = facadeService;
            _mapper = mapper;
            _uow = uow;
        }
        #endregion

        [BindProperty]
        [PageRemote(PageName = "CreateSeller", PageHandler = "CheckForShopName",
            HttpMethod = "POST",
            AdditionalFields = ViewModelConstants.AntiForgeryToken,
            ErrorMessage = AttributesErrorMessages.RemoteMessage)]
        [Display(Name = "نام فروشگاه")]
        [Required(ErrorMessage = AttributesErrorMessages.RequiredMessage)]
        [MaxLength(200, ErrorMessage = AttributesErrorMessages.MaxLengthMessage)]
        public string ShopName { get; set; }

        [BindProperty]
        public CreateSellerViewModel CreateSeller { get; set; } = new();
        public async Task<IActionResult> OnGet(string phoneNumber)
        {

            if (!await _userManager.CheckForUserIsSeller(phoneNumber))
            {
                return RedirectToPage("~/Error");
            }

            CreateSeller.PhoneNumber = phoneNumber;
            var provinces = await _facadeService
                .ProvinceAndCityService.GetProvincesToShowInSelectBoxAsync();

            CreateSeller = await _userManager.GetUserInfoForCreateSeller(phoneNumber);
            CreateSeller.Provinces = provinces.CreateSelectListItem();
            return Page();
        }
        //public void OnGet()
        //{
        //}
        public async Task<IActionResult> OnPost()
        {
            //await _signInManager.SignInAsync(user, true);
            if (!ModelState.IsValid)
            {
                return Json(new JsonResultOperation(false, PublicConstantStrings.ModelStateErrorMessage)
                {
                    Data = ModelState.GetModelStateErrors()
                });
            }

            if (!CreateSeller.IsLegalPerson)
            {
                CreateSeller.CompanyName
                    = CreateSeller.RegisterNumber
                        = CreateSeller.EconomicCode
                            = CreateSeller.SignatureOwners
                                = CreateSeller.NationalId
                                    = null;
                CreateSeller.CompanyType = null;

            }
            else
            {
                var legalPersonProperties = new List<string>
                {
                    nameof(CreateSeller.CompanyName),
                    nameof(CreateSeller.RegisterNumber),
                    nameof(CreateSeller.EconomicCode),
                    nameof(CreateSeller.SignatureOwners),
                    nameof(CreateSeller.NationalId)
                };

                ModelState.CheckStringInputs(legalPersonProperties, CreateSeller);
                if (!ModelState.IsValid)
                {
                    return Json(new JsonResultOperation(false, PublicConstantStrings.ModelStateErrorMessage)
                    {
                        Data = ModelState.GetModelStateErrors()
                    });
                }
            }

            var user = await _userManager.GetUserForCreateSeller(CreateSeller.PhoneNumber);
            if (user is null)
            {
                return Json(new JsonResultOperation(false, "کاربر مورد نظر یافت نشد"));
            }

            user = _mapper.Map(CreateSeller, user);

            var birthDateResult = CreateSeller.BirthDate.ToGregorianDateForCreateSeller();
            if (!birthDateResult.IsOk)
            {
                return Json(new JsonResultOperation(false, "تاریخ تولد را به درستی وارد نمایید"));
            }

            if (!birthDateResult.IsRangeOk)
            {
                return Json(new JsonResultOperation(false, "سن شما باید بیشتر از ۱۸ سال باشد"));
            }

            user.BirthDate = birthDateResult.ConvertedDateTime;

            var seller = _mapper.Map<MarketKhoone.Entities.Seller>(CreateSeller);
            seller.UserId = user.Id;
            seller.ShopName = ShopName;
            seller.IsRealPerson = !CreateSeller.IsLegalPerson;
            string logoFileName = null;
            if (CreateSeller.LogoFile.IsFileUploaded())
                logoFileName = CreateSeller.LogoFile.GenerateFileName();


            seller.IdCartPicture = CreateSeller.IdCartPictureFile.GenerateFileName();
            seller.Logo = logoFileName;

            seller.SellerCode = await _facadeService.SellerService.GetSellerCodeForCreateSeller();

            var result = await _facadeService.SellerService.AddAsync(seller);
            if (!result.Ok)
            {
                return Json(new JsonResultOperation(false, PublicConstantStrings.DuplicateErrorMessage)
                {
                    Data = result.Columns.SetDuplicateColumnsErrorMessages<CreateSellerViewModel>()
                });
            }

            var roleResult = await _userManager.AddToRoleAsync(user, ConstantRoles.Seller);
            if (!roleResult.Succeeded)
            {
                ModelState.AddErrorsFromResult(roleResult);
                return Json(new JsonResultOperation(false)
                {
                    Data = ModelState.GetModelStateErrors()
                });
            }

            await _uow.SaveChangesAsync();

            await _facadeService.UploadedFileService.SaveFile(CreateSeller.IdCartPictureFile, seller.IdCartPicture,
                null, "images", "seller-id-cart-pictures");
            if (logoFileName != null)
                await _facadeService.UploadedFileService.SaveFile(CreateSeller.LogoFile, logoFileName, null,
                    "images", "seller-logos");
            return Json(new JsonResultOperation(true, "شما با موفقیت به عنوان فروشنده انتخاب شدید")
            {
                Data = "/Seller/RegistrationDone"
            });
        }
        public async Task<IActionResult> OnGetGetCities(long provinceId)
        {
            if (provinceId == 0)
            {
                return Json(new JsonResultOperation(true, string.Empty)
                {
                    Data = new Dictionary<long, string>()
                });
            }

            if (provinceId < 1)
            {
                return Json(new JsonResultOperation(false, "استان مورد نظر را به درستی وارد نمایید"));
            }

            if (!await _facadeService.ProvinceAndCityService.IsExistsBy(
                    nameof(MarketKhoone.Entities.ProvinceAndCity.Id), provinceId))
            {
                return Json(new JsonResultOperation(false, "استان مورد نظر یافت نشد"));
            }

            var cities = await _facadeService.ProvinceAndCityService.GetCitiesByProvinceIdInSelectBoxAsync(provinceId);
            return Json(new JsonResultOperation(true, string.Empty)
            {
                Data = cities
            });
        }
        public async Task<IActionResult> OnPostCheckForShopName(string shopName)
        {
            return Json(!await _facadeService.SellerService.IsExistsBy(nameof(MarketKhoone.Entities.Seller.ShopName),
                shopName));
        }
        public async Task<IActionResult> OnGetCheckForShabaNumber(CreateSellerViewModel createSeller)
        {
            return Json(!await _facadeService.SellerService.IsExistsBy(nameof(MarketKhoone.Entities.Seller.ShabaNumber),
                createSeller.ShabaNumber));
        }
    }
}

src/Marketkhoone.Web/Pages/Seller/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MarketKhoone.Web.Pages.Seller;

public class ErrorModel : PageModel
{
    public void OnGet()
    {
    }
}

src/Marketkhoone.Web/Pages/Admin/Seller/SellerDetails.cshtml
@model MarketKhoone.ViewModels.Sellers.SellerDetailsViewModel
@using MarketKhoone.Entities.Enums.Seller
@using MarketKhoone.Entities.Enums.User
@using MarketKhoone.Common.Helpers
@{
    var isRealPerson = Model.IsRealPerson;
    var documentStatusButtonClass = string.Empty;
    if (Model.DocumentStatus is DocumentStatus.AwaitingApprovalSystemSeller
        or DocumentStatus.AwaitingInitialApproval)
        documentStatusButtonClass = "warning";
    else if (Model.DocumentStatus == DocumentStatus.Confirmed)
        documentStatusButtonClass = "success";
    else
        documentStatusButtonClass = "danger";
    var isActive = Model.IsActive;

}
<div class="card">
    <div class="card-header">
        <div class="card-title">
            اطلاعات کامل فروشگاه
            <b>@Model.ShopName</b>
            با مدیریت
            <b>@Model.UserFullName</b>
        </div>
    </div>
    <div class="card-body">
        <div class="row">
            <div>
                <p class="fw-bold">
                    <span class="btn btn-info">
                        @Model.UserPhoneNumber
                    </span>
                    <span class="btn btn-@(isRealPerson ? "success" : "primary")">
                        @(isRealPerson ? "شخص حقیقی" : "شخص حقوقی")
                    </span>
                    <span class="btn btn-@documentStatusButtonClass">
                        @Model.DocumentStatus.GetEnumDisplayName()
                    </span>
                    <span class="btn btn-info">
                        @if (Model.UserGender == Gender.Man)
                        {
                            <text>آقا</text>
                            <i class="bi bi-person-fill"></i>
                        }
                        else
                        {
                            @:خانم
                            <i class="bi bi-person-heart"></i>
                        }
                    </span>
                    <span class="btn btn-dark">
                        @Model.CreatedDateTime
                    </span>
                    <span class="btn btn-@(isActive ? "success" : "danger")">
                        @(isActive ? "فعال" : "غیر فعال")
                    </span>
                </p>
            </div>
            @if (!isRealPerson)
            {
                <div class="row">
                    <div class="col-md-4 col-lg-3">
                        <p class="fw-bold">
                            @Html.DisplayNameFor(x=> x.CompanyName)
                        </p>
                        <p>
                            @Model.CompanyName
                        </p>
                    </div>
                    <div class="col-md-4 col-lg-3">
                        <p class="fw-bold">
                            @Html.DisplayNameFor(x=> x.RegisterNumber)
                        </p>
                        <p>
                            @Model.RegisterNumber
                        </p>
                    </div>
                    <div class="col-md-4 col-lg-3">
                        <p class="fw-bold">
                            @Html.DisplayNameFor(x=> x.EconomicCode)
                        </p>
                        <p>
                            @Model.EconomicCode
                        </p>
                    </div>
                    <div class="col-md-4 col-lg-3">
                        <p class="fw-bold">
                            @Html.DisplayNameFor(x=> x.SignatureOwners)
                        </p>
                        <p>
                            @Model.SignatureOwners
                        </p>
                    </div>
                    <div class="col-md-4 col-lg-3">
                        <p class="fw-bold">
                            @Html.DisplayNameFor(x=> x.NationalId)
                        </p>
                        <p>
                            @Model.NationalId
                        </p>
                    </div>
                    <div class="col-md-4 col-lg-3">
                        <p class="fw-bold">
                            @Html.DisplayNameFor(x=> x.CompanyType)
                        </p>
                        <p>
                            @Model.CompanyType?.GetEnumDisplayName()
                        </p>
                    </div>
                </div>
                <hr />
            }
            <div class="row">
                <div class="col-md-4 col-lg-3">
                    <p class="fw-bold">
                        @Html.DisplayNameFor(x=> x.Id)
                    </p>
                    <p>
                        @Model.Id
                    </p>
                </div>
                <div class="col-md-4 col-lg-3">
                    <p class="fw-bold">
                        @Html.DisplayNameFor(x=> x.UserFirstName)
                    </p>
                    <p>
                        @Model.UserFullName
                    </p>
                </div>
                <div class="col-md-4 col-lg-3">
                    <p class="fw-bold">
                        @Html.DisplayNameFor(x=> x.UserLastName)
                    </p>
                    <p>
                        @Model.UserFullName
                    </p>
                </div>
                <div class="col-md-4 col-lg-3">
                    <p class="fw-bold">
                        @Html.DisplayNameFor(x=> x.SellerCode)
                    </p>
                    <p>
                        @Model.SellerCode
                    </p>
                </div>
                <div class="col-md-4 col-lg-3">
                    <p class="fw-bold">
                        @Html.DisplayNameFor(x=> x.ShopName)
                    </p>
                    <p>
                        @Model.ShopName
                    </p>
                </div>
                <div class="col-md-4 col-lg-3">
                    <p class="fw-bold">
                        @Html.DisplayNameFor(x=> x.Logo)
                    </p>
                    <p>
                        @if (Model.Logo is null)
                        {
                            <span class="btn btn-primary">بدون لوگو</span>
                        }
                        else
                        {
                            <img width="100" src="~/images/seller-logos/@Model.Logo" alt="لوگو فروشگاه @Model.ShopName" />
                        }
                    </p>
                </div>
                <div class="col-md-4 col-lg-3">
                    <p class="fw-bold">
                        @Html.DisplayNameFor(x=> x.IdCartPicture)
                    </p>
                    <p>
                        <img width="100" src="~/images/seller-id-cart-pictures/@Model.IdCartPicture" alt="تصویر کارت ملی" />
                    </p>
                </div>
                <div class="col-md-4 col-lg-3">
                    <p class="fw-bold">
                        @Html.DisplayNameFor(x=> x.ShabaNumber)
                    </p>
                    <p>
                        IR @Model.ShabaNumber
                    </p>
                </div>
                <div class="col-md-4 col-lg-3">
                    <p class="fw-bold">
                        @Html.DisplayNameFor(x=> x.Telephone)
                    </p>
                    <p>
                        @Model.Telephone
                    </p>
                </div>
                <div class="col-md-4 col-lg-3">
                    <p class="fw-bold">
                        @Html.DisplayNameFor(x=> x.Website)
                    </p>
                    <p>
                        <a href="@Model.Website" target="_blank">@Model.Website</a>
                    </p>
                </div>
                <div class="col-md-4 col-lg-3">
                    <p class="fw-bold">
                        @Html.DisplayNameFor(x=> x.ProvinceTitle)
                    </p>
                    <p>
                        @Model.ProvinceTitle
                    </p>
                </div>
                <div class="col-md-4 col-lg-3">
                    <p class="fw-bold">
                        @Html.DisplayNameFor(x=> x.CityTitle)
                    </p>
                    <p>
                        @Model.CityTitle
                    </p>
                </div>
                <div class="col-md-4 col-lg-3">
                    <p class="fw-bold">
                        @Html.DisplayNameFor(x=> x.PostalCode)
                    </p>
                    <p>
                        @Model.PostalCode
                    </p>
                </div>
                <div class="col-lg-9">
                    <p class="fw-bold">
                        @Html.DisplayNameFor(x=> x.Address)
                    </p>
                    <p>
                        @Model.Address
                    </p>
                </div>
                <div>
                    <p class="fw-bold">
                        @Html.DisplayNameFor(x=> x.AboutSeller)
                    </p>
                    <p>
                        @Html.Raw(Model.AboutSeller)
                    </p>
                </div>
                <hr />
            </div>
        </div>
    </div>
<div class="container">
    @if (Model.DocumentStatus != DocumentStatus.Confirmed)
    {
        <form functionNameToCallInTheEnd="sellerDocumentInManagingSellers"
              method="post" asp-page-handler="RejectSellerDocuments" class="public-ajax-form">
            <input asp-for="Id" />
            <div class="text-danger" asp-validation-summary="All"></div>
            <div class="m-2">
                <label asp-for="RejectReason" class="mb-3 form-label"></label>
                <textarea asp-for="RejectReason" class="custom-tinymce"></textarea>
                <span asp-validation-for="RejectReason" class="span-error-message"></span>
            </div>
            <button class="btn btn-warning" id="btn1">ارسال مشکلات مدارکی فروشنده</button>

        </form>
    }
    @if (Model.DocumentStatus == DocumentStatus.AwaitingApprovalSystemSeller ||
    Model.DocumentStatus == DocumentStatus.AwaitingInitialApproval)
    {

        <form functionNameToCallInTheEnd="sellerDocumentInManagingSellers"
              method="post" asp-page-handler="ConfirmSellerDocuments"
              class="m-2 public-ajax-form">
            <input asp-for="Id" />
            <button class="btn btn-danger" id="btn2">تایید کردن مدارک فروشنده</button>
        </form>

        <form functionNameToCallInTheEnd="sellerDocumentInManagingSellers"
              method="post" asp-page-handler="RemoveSeller"
              class="m-2 public-ajax-form">
            <input asp-for="Id" />
            <button type="button" class="delete-row-button btn btn-danger" id="btn3">حذف فروشنده</button>
        </form>

    }
</div>
</div>