src/Marketkhoone.Web/Pages/Admin/Product/Index.cshtml.cs
using EShopMarket.Common.Helpers;
using Ganss.Xss;
using MarketKhoone.Common;
using MarketKhoone.Common.Constants;
using MarketKhoone.Common.IdentityToolkit;
using MarketKhoone.DataLayer.Context;
using MarketKhoone.Entities.Enums.Product;
using MarketKhoone.Services.Contracts.IFacadePattern;
using MarketKhoone.ViewModels.Products;
using Microsoft.AspNetCore.Mvc;

namespace Marketkhoone.Web.Pages.Admin.Product
{
    public class IndexModel : PageBase
    {
        #region Constructor

        private readonly IFacadeServices _facadeServices;
        private readonly IUnitOfWork _uow;
        private readonly IHtmlSanitizer _htmlSanitizer;

        public IndexModel(IFacadeServices facadeServices, IUnitOfWork uow, IHtmlSanitizer htmlSanitizer)
        {
            _facadeServices = facadeServices;
            _uow = uow;
            _htmlSanitizer = htmlSanitizer;
        }

        #endregion

        [BindProperty(SupportsGet = true)]
        public ShowProductsViewModel Products { get; set; } = new();
        public void OnGet()
        {
            //آپشن داخل سلکت ما الان ولیو دارد، اما ولیوش خالیه
            Products.SearchProducts.Categories = _facadeServices.CategoryService.GetCategoriesWithNoChild()
                .Result.CreateSelectListItem(firstItemText: "همه", firstItemValue: string.Empty);
        }
        public async Task<IActionResult> OnGetGetDataTableAsync()
        {
            if (!ModelState.IsValid)
            {
                return Json(new JsonResultOperation(false, PublicConstantStrings.ModelStateErrorMessage)
                {
                    Data = ModelState.GetModelStateErrors()
                });
            }
            return Partial("List", await _facadeServices.ProductService.GetProducts(Products));
        }

        public async Task<IActionResult> OnGetGetProductDetails(long productId)
        {
            var product = await _facadeServices.ProductService.GetProductDetails(productId);

            if (product is null)
            {
                return Json(new JsonResultOperation(false, PublicConstantStrings.RecordNotFoundMessage));
            }

            return Partial("ProductDetails", product);
        }

        public async Task<IActionResult> OnPostRemoveProduct(long id)
        {
            if (id < 1)
            {
                return Json(new JsonResultOperation(false));
            }

            var product = await _facadeServices.ProductService.GetProductToRemoveInManagingProducts(id);
            if (product is null)
            {
                return Json(new JsonResultOperation(false, PublicConstantStrings.RecordNotFoundMessage));
            }

            var productShortLink =
                await _facadeServices.ProductShortLinkService.FindByIdAsync(product.ProductShortLinkId);

            //چون بالا بررسی کردیم که آیا پروداکت وجود داره یا نداره
            //اینجا مطمئنیم حتما پروداکت شورت لینک وجود داره
            productShortLink.IsUsed = false;

            _facadeServices.ProductService.Remove(product);
            await _uow.SaveChangesAsync();
            foreach (var media in product.ProductMedia)
            {
                _facadeServices.UploadedFileService.DeleteFile(media.FileName,
                    media.IsVideo ? "videos" : "images", "products");
            }
            return Json(new JsonResultOperation(true, "محصول موزد نظر با موفقیت حذف شد"));
        }

        public async Task<IActionResult> OnPostRejectProduct(ProductDetailsViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return Json(new JsonResultOperation(false, "لطفا دلایل رد برند را وارد نمایید"));
            }

            var product = await _facadeServices.ProductService.FindByIdAsync(model.Id);
            if (product is null)
            {
                return Json(new JsonResultOperation(false, PublicConstantStrings.RecordNotFoundMessage));
            }

            product.Status = ProductStatus.Rejected;
            product.RejectReason = _htmlSanitizer.Sanitize(model.RejectReason);
            await _uow.SaveChangesAsync();
            return Json(new JsonResultOperation(true, "محصول مورد نظر با موفقیت رد شد"));

        }

        public async Task<IActionResult> OnPostConfirmProduct(long id, Dimension dimension)
        {
            if (id < 1)
            {
                return Json(new JsonResultOperation(false));
            }

            var product = await _facadeServices.ProductService.FindByIdAsync(id);
            if (product is null)
            {
                return Json(new JsonResultOperation(false, PublicConstantStrings.RecordNotFoundMessage));
            }

            product.Status = ProductStatus.Confirmed;
            product.Dimension = dimension;
            product.RejectReason = null;
            await _uow.SaveChangesAsync();
            return Json(new JsonResultOperation(true, "محصول مورد نظر با موفقیت تایید شد"));
        }

        public async Task<IActionResult> OnGetAutocompleteSearchForPersianTitle(string term)
        {
            return Json(await _facadeServices.ProductService.GetPersianTitlesForAutocomplete(term));
        }

        public async Task<IActionResult> OnGetAutocompleteSearchForShopName(string term)
        {
            return Json(await _facadeServices.SellerService.GetShopNamesForAutocomplete(term));
        }
    }
}

src/Marketkhoone.Web/Pages/Product/ProductShortLink.cshtml.cs
using MarketKhoone.Common.Constants;
using MarketKhoone.Services.Contracts.IFacadePattern;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Text;
using System.Text.RegularExpressions;

namespace Marketkhoone.Web.Pages.Product
{
    public class ProductShortLinkModel : PageModel
    {
        #region Constructor

        private readonly IFacadeServices _facadeServices;
        public ProductShortLinkModel(IFacadeServices facadeServices)
        {
            _facadeServices = facadeServices;
        }

        #endregion

        public async Task<IActionResult> OnGet(string productsShortLink)
        {
            if (!Regex.IsMatch(productsShortLink, @"^[a-zA-Z0-9]{1,10}$"))
            {
                return RedirectToPage(PublicConstantStrings.Error404PageName);
            }

            var shortLinkInBytes = Encoding.UTF8.GetBytes(productsShortLink);
            var shortLinkToCompare = string.Join(".", shortLinkInBytes);
            var product = await _facadeServices.ProductService.FindByShortLink(shortLinkToCompare);
            if (product.slug is null)
            {
                return RedirectToPage(PublicConstantStrings.Error404PageName);
            }

            return RedirectToPagePermanent("/Product/Index", new
            {
                product.slug,
                product.productCode
            });
        }
    }
}

src/Marketkhoone.Web/Pages/SellerPanel/Consignment/ConfirmationConsignment.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Marketkhoone.Web.Pages.SellerPanel.Consignment
{
    public class ConfirmationConsignmentModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

src/Marketkhoone.Web/Pages/SellerPanel/Index.cshtml.cs
namespace Marketkhoone.Web.Pages.SellerPanel
{
    public class IndexModel : SellerPanelBase
    {
        #region Constructor
        #endregion
        public void OnGet()
        {
        }
    }
}

src/Marketkhoone.Web/Pages/SellerPanel/Product/All.cshtml.cs
using EShopMarket.Common.Helpers;
using MarketKhoone.Common;
using MarketKhoone.Common.Constants;
using MarketKhoone.Common.IdentityToolkit;
using MarketKhoone.Services.Contracts.IFacadePattern;
using MarketKhoone.ViewModels.Products;
using Microsoft.AspNetCore.Mvc;

namespace Marketkhoone.Web.Pages.SellerPanel.Product
{
    public class AllModel : SellerPanelBase
    {

        #region Constructor
        private readonly IFacadeServices _facadeService;
        public AllModel(IFacadeServices facadeService)
        {
            _facadeService = facadeService;
        }
        #endregion

        [BindProperty(SupportsGet = true)]
        public ShowAllProductsInSellerPanelViewModel Products { get; set; } = new(); 
        public void OnGet()
        {
            Products.SearchProducts.Categories = _facadeService.CategoryService.GetCategoriesWithNoChild()
                .Result.CreateSelectListItem(firstItemText: "aaa", firstItemValue: string.Empty);
        }

        public async Task<IActionResult> OnGetGetDataTableAsync()
        {
            if (!ModelState.IsValid)
            {
                return Json(new JsonResultOperation(false, PublicConstantStrings.ModelStateErrorMessage)
                {
                    Data = ModelState.GetModelStateErrors()
                });
            }

            return Partial("ListForAll", await _facadeService.ProductService.GetAllProductsInSellerPanel(Products));
        }

        public async Task<IActionResult> OnGetGetProductDetails(long productId)
        {
            var product = await _facadeService.ProductService.GetProductDetails(productId);
            if (product is null)
            {
                return Json(new JsonResultOperation(false, PublicConstantStrings.RecordNotFoundMessage));
            }

            return Partial("ProductDetails", product);
        }

        public async Task<IActionResult> OnGetAutocompleteSearchPersianTitle(string term)
        {
            return Json(await _facadeService.ProductService.GetPersianTitlesForAutocomplete(term));
        }
    }


}

src/Marketkhoone.Web/Pages/SellerPanel/Product/Index.cshtml.cs
using AutoMapper;
using DNTPersianUtils.Core;
using EShopMarket.Common.Helpers;
using MarketKhoone.Common;
using MarketKhoone.Common.Attributes;
using MarketKhoone.Common.Constants;
using MarketKhoone.Common.Helpers;
using MarketKhoone.DataLayer.Context;
using MarketKhoone.Services.Contracts.IFacadePattern;
using MarketKhoone.ViewModels.Products;
using MarketKhoone.ViewModels.ProductVariants;
using Microsoft.AspNetCore.Mvc;

namespace Marketkhoone.Web.Pages.SellerPanel.Product
{
    [CheckModelStateInRazorPages]
    public class IndexModel : SellerPanelBase
    {
        #region Constructor

        private readonly IFacadeServices _facadeServices;
        private readonly IMapper _mapper;
        private readonly IUnitOfWork _uow;

        public IndexModel(IFacadeServices facadeServices, IMapper mapper, IUnitOfWork uow)
        {
            _facadeServices = facadeServices;
            _mapper = mapper;
            _uow = uow;
        }

        #endregion

        [BindProperty(SupportsGet = true)]
        public ShowProductsInSellerPanelViewModel Products { get; set; } = new();
        public void OnGet()
        {
            Products.SearchProducts.Categories = _facadeServices.CategoryService.GetSellerCategories()
                .Result.CreateSelectListItem(firstItemText: "همه", firstItemValue: string.Empty);
        }

        public async Task<IActionResult> OnGetGetDataTableAsync()
        {
            return Partial("List", await _facadeServices.ProductService.GetProductsInSellerPanel(Products));
        }

        public async Task<IActionResult> OnGetGetProductDetails(long productId)
        {
            var product = await _facadeServices.ProductService.GetProductDetails(productId);
            if (product is null)
            {
                return Json(new JsonResultOperation(false, PublicConstantStrings.RecordNotFoundMessage));
            }

            return Partial("ProductDetails", product);
        }

        public async Task<IActionResult> OnGetAutocompleteSearchForPersianTitle(string term)
        {
            return Json(await _facadeServices.ProductService.GetPersianTitlesForAutocompleteInSellerPanel(term));
        }

        public async Task<IActionResult> OnGetShowProductVariantsAsync(long productId)
        {
            if (productId < 1)
            {
                return Json(new JsonResultOperation(false));
            }

            return Partial("ProductVariants",
                await _facadeServices.ProductVariantService.GetProductVariants(productId));
        }

        public async Task<IActionResult> OnGetEditProductVariant(long productVariantId)
        {
            if (productVariantId < 1)
            {
                return Json(new JsonResultOperation(false));
            }

            var productVariant = await _facadeServices.ProductVariantService.GetDataForEdit(productVariantId);

            if (productVariant is null)
            {
                return Json(new JsonResultOperation(false, PublicConstantStrings.RecordNotFoundMessage));
            }

            return Partial("_EditProductVariantPartial", productVariant);
        }

        public async Task<IActionResult> OnPostEditProductVariant(EditProductVariantViewModel model)
        {
            if (ModelState.IsValid)
            {
                return Json(new JsonResultOperation(false, PublicConstantStrings.ModelStateErrorMessage));
            }

            var productVariantToEdit = await _facadeServices.ProductVariantService.GetForEdit(model.Id);

            if (productVariantToEdit is null)
            {
                return Json(new JsonResultOperation(false));
            }

            productVariantToEdit = _mapper.Map(model, productVariantToEdit);
            productVariantToEdit.StartDateTime = productVariantToEdit.EndDateTime = null;
            productVariantToEdit.OffPrice = productVariantToEdit.OffPercentage = null;

            await _uow.SaveChangesAsync();
            return Json(new JsonResultOperation(true, "تنوع محصول نظر با موفقیت ویرایش شد"));
        }

        public async Task<IActionResult> OnGetAddEditDiscount(long productVariantId)
        {
            if (productVariantId < 1)
            {
                return Json(new JsonResultOperation(false));
            }

            var productVariant =
                await _facadeServices.ProductVariantService.GetDataForAddEditDiscount(productVariantId);

            if (productVariant is null)
            {
                return Json(new JsonResultOperation(false, PublicConstantStrings.RecordNotFoundMessage));
            }

            return Partial("_AddEditDiscountPartial", productVariant);
        }

        public async Task<IActionResult> OnPostAddEditDiscount(AddEditDiscountViewModel model)
        {
            var productVariant = await _facadeServices.ProductVariantService.GetForEdit(model.Id);
            if (productVariant is null)
            {
                return Json(new JsonResultOperation(false, PublicConstantStrings.RecordNotFoundMessage));
            }

            var parsedDateTimes =
                DateTimeHelper.ConvertDateTimeForAddEditDiscount(model.StartDateTime, model.EndDateTime);
            if (!parsedDateTimes.IsSuccessful)
            {
                return Json(new JsonResultOperation(false, "لطفا تاریخ ها را به درستی وارد نمایید"));
            }

            if (parsedDateTimes.IsStartDateTimeGreatherOrEqualEndDateTime)
            {
                return Json(new JsonResultOperation(false, "تاریخ پایان تخفیف باید بزرگتر از تاریخ شروع تخفیف باشد"));

            }

            if (parsedDateTimes.IsTimeSpanLowerThan3Hour)
            {
                return Json(new JsonResultOperation(false,
                    "تاریخ پایان تخفیف باید حداقل 3 ساعت بزگتر از تاریخ شروع تخفیف باشد"));
            }

            var offPrice = model.OffPrice;
            var price = productVariant.Price;
            var offPercentage = model.OffPercentage;
            var discountPrice = price / 100 * offPercentage;
            var priceWithDiscount = price - discountPrice;
            var discountPricesSubtract1Percentage = price / 100 * (offPercentage - 1);
            var priceWithDiscountSubtract1Percentage = price - discountPricesSubtract1Percentage;


            if (offPrice < priceWithDiscount || offPrice >= priceWithDiscountSubtract1Percentage)
            {
                return Json(new JsonResultOperation(false,
                    $"قیمت تخفیف باید بزگتر و مساوی{priceWithDiscount.ToString("#,0").ToPersianNumbers()}تومان و کوچکتر از {priceWithDiscountSubtract1Percentage.ToString("#,0").ToPersianNumbers()}تومان باشد"));
            }

            productVariant.StartDateTime = parsedDateTimes.StartDate;
            productVariant.EndDateTime = parsedDateTimes.EndDate;
            _mapper.Map(model, productVariant);

            // todo: Send notices to the users
            // todo: remove all notices records

            await _uow.SaveChangesAsync();
            return Json(new JsonResultOperation(true, "تنوع محصول مورد نظر با موفقیت ویرایش شد"));
        }
    }
}

src/Marketkhoone.Web/Pages/SellerPanel/Product/Successful.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Marketkhoone.Web.Pages.SellerPanel.Product
{
    public class SuccessfulModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

src/Marketkhoone.Web/Pages/SellerPanel/Product/SuccessfulProductVariant.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Marketkhoone.Web.Pages.SellerPanel.Product
{
    public class SuccessfulProductVariantModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

src/Marketkhoone.Web/Pages/SellerPanel/Product/ProductDetails.cshtml
@using MarketKhoone.Entities.Enums.Product
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using MarketKhoone.Common.Helpers
@model MarketKhoone.ViewModels.Products.ProductDetailsViewModel
@{
    var statusButtonClass = Model.Status switch
    {
        ProductStatus.Confirmed => "success",
        ProductStatus.Rejected => "danger",
        _ => "warning"
    };
}
<div class="card">
    <div class="card-header">
        <div class="card-title">
            جزییات محصول
            <b>
                <a asp-page="/Product/Index" asp-route-productCode="@Model.ProductCode" asp-route-slug="@Model.Slug">
                    @Model.PersianTitle
                </a>
            </b>

        </div>
    </div>
    <div class="card-body">
        <div class="row">
            <div>
                <p class="fw-bold">
                    <span class="btn btn-primary" data-bs-toggle="collapse" data-bs-target="#product-files-collapse">
                        فایل (ها) |
                        تعداد عکس :@Model.ProductMedia.Count(x=> !x.IsVideo)
                        تعداد ویدیو :@Model.ProductMedia.Count(x=> x.IsVideo)
                    </span>
                    <span class="btn btn-primary" data-bs-toggle="collapse" data-bs-target="#product-features-collapse">
                        ویژگی های محصول: @Model.ProductFeatures.Count
                    </span>
                    <span class="btn btn-info">
                        @if (Model.IsFake)
                        {
                            @:محصول غیر اصل میباشد
                        }
                        else
                        {
                            <text>اصل</text>
                        }
                    </span>
                    <span class="btn btn-@(statusButtonClass)">
                        وضعیت:
                        @Model.Status.GetEnumDisplayName()
                    </span>
                    <span class="btn btn-primary">
                        دسته بندی اصلی:
                        @Model.CategoryTitle
                    </span>
                    @if (Model.Status == ProductStatus.Confirmed)
                    {
                        <span class="btn btn-primary">
                            @Html.DisplayNameFor(x=> x.Dimension):
                            @Model.Dimension.GetEnumDisplayName()
                        </span>
                    }
                </p>
            </div>
            <div class="row">
                <div class="collapse" id="product-files-collapse">
                    <div class="card card-body d-inline-block w-100">
                        @foreach (var image in Model.ProductMedia.Where(x => !x.IsVideo))
                        {
                            <img src="~/images/products/@image.FileName" width="100" />
                        }
                        @foreach (var video in Model.ProductMedia.Where(x => x.IsVideo))
                        {
                            <video class="product-videos-managing-sellers" controls>
                                <source src="~/videos/products/@video.FileName" width="100">
                                مرورگر شما از تگ ویدیو پشتیبانی نمیکند
                            </video>
                        }
                    </div>
                </div>
                <div class="collapse" id="product-features-collapse">
                    <div class="card card-body d-inline-block w-100">
                        @foreach (var feature in Model.ProductFeatures)
                        {
                            <p>
                                @feature.FeatureTitle:
                                @foreach (var value in feature.Value.Split("|||"))
                                {
                                    <span class="badge bg-primary">@value</span>
                                }
                            </p>
                        }
                    </div>
                </div>
                <div class="col-md-4 col-lg-3">
                    <p class="fw-bold">
                        @Html.DisplayNameFor(x => x.EnglishTitle)
                    </p>
                    <p>
                        @(Model.EnglishTitle ?? "ندارد")
                    </p>
                </div>
                <div class="col-md-4 col-lg-3">
                    <p class="fw-bold">
                        @Html.DisplayNameFor(x => x.PackWeight)
                    </p>
                    <p>
                        @Model.PackWeight
                        گرم
                    </p>
                </div>
                <div class="col-md-4 col-lg-3">
                    <p class="fw-bold">
                        @Html.DisplayNameFor(x => x.PackLength)
                    </p>
                    <p>
                        @Model.PackLength
                        سانتیمتر
                    </p>
                </div>
                <div class="col-md-4 col-lg-3">
                    <p class="fw-bold">
                        @Html.DisplayNameFor(x => x.PackWidth)
                    </p>
                    <p>
                        @Model.PackWidth
                        سانتیمتر
                    </p>
                </div>
                <div class="col-md-4 col-lg-3">
                    <p class="fw-bold">
                        @Html.DisplayNameFor(x => x.PackHeight)
                    </p>
                    <p>
                        @Model.PackWeight
                        سانتیمتر
                    </p>
                </div>
                <div class="col-md-4 col-lg-3">
                    <p class="fw-bold">
                        @Html.DisplayNameFor(x => x.SellerShopName)
                    </p>
                    <p>
                        @Model.SellerShopName
                    </p>
                </div>
                <div class="col-md-4 col-lg-3">
                    <p class="fw-bold">
                        @Html.DisplayNameFor(x => x.BrandFullTitle)
                    </p>
                    <p>
                        @Model.BrandFullTitle
                    </p>
                </div>
                <div>
                    <p class="fw-bold">
                        @Html.DisplayNameFor(x => x.ShortDescription)
                    </p>
                    <p>
                        @if (!string.IsNullOrWhiteSpace(Model.ShortDescription))
                        {
                            <text>بدون توضیح</text>
                        }
                        else
                        {
                            @Model.ShortDescription
                        }
                    </p>
                </div>
                <div>
                    <p class="fw-bold">
                        @Html.DisplayNameFor(x => x.SpecialtyCheck)
                    </p>
                    <p>
                        @if (!string.IsNullOrWhiteSpace(Model.SpecialtyCheck))
                        {
                            <text>بدون توضیح</text>
                        }
                        else
                        {
                            @Model.SpecialtyCheck
                        }
                    </p>
                </div>
                @if (Model.Status == ProductStatus.AwaitingInitialApproval)
                {
                    <hr />
                    <form functionNameToCallInTheEnd="productStatusInManagingProducts"
                          method="post" asp-page-handler="RejectProduct" class="public-ajax-form">
                        <input asp-for="Id" />
                        <div class="text-danger" asp-validation-summary="All"></div>
                        <div class="mb-3">
                            <label asp-for="RejectReason" class="mb-3 form-label"></label>
                            <textarea asp-for="RejectReason" class="custom-tinymce"></textarea>
                            <span asp-validation-for="RejectReason" class="span-error-message"></span>
                        </div>
                        <button type="submit" class="btn btn-warning">ارسال مشکلات محصول</button>
                    </form>

                    <form functionNameToCallInTheEnd="productStatusInManagingProducts"
                          method="post" asp-page-handler="ConfirmProduct"
                          class="mt-3 public-ajax-form">
                        <input asp-for="Id" />

                        <div class="mb-3">
                            <label asp-for="Dimension" class="form-label"></label>
                            <select class="form-select" asp-for="Dimension" asp-items="Html.GetEnumSelectList<MarketKhoone.Entities.Enums.Product.Dimension>()">
                            </select>
                        </div>

                        <button type="submit" class="btn btn-success">تایید کردن محصول</button>
                    </form>
                }

                @if (Model.Status == ProductStatus.AwaitingInitialApproval)
                {
                    <form functionNameToCallInTheEnd="productStatusInManagingProducts"
                          method="post" asp-page-handler="RemoveProduct"
                          class="mt-3 public-ajax-form">
                        <input asp-for="Id" />
                        <button type="button" class="delete-row-button btn btn-danger">حذف دائمی محصول</button>
                    </form>
                }
            </div>
        </div>
    </div>
</div>

src/Marketkhoone.Web/Pages/SellerPanel/Product/Successful.cshtml
@page
@model Marketkhoone.Web.Pages.SellerPanel.Product.SuccessfulModel
@{
    ViewData["Title"] = "محصول مورد نظر با موفقیت ایجاد شد";
}
<div class="row justify-content-center">
    <div class="col-lg-8 alert alert-success text-center">
        <h4 class="alert-heading">
            <i class="bi bi-info-circle-fill text-info"></i>
            محصول ایجاد شد
        </h4>
        محصول مورد نظر با موفقیت ایجاد شد،
        پس از تایید شدن محصول توسط کارشناسان
        <a asp-page="/Index">
            مارکت خونه
        </a>
        میتوانید برای این محصول موجودی اضافه کنید؛
        مراتب از طریق ایمیل به شما اطلاع رسانی خواهد شد.
    </div>
</div>

src/Marketkhoone.Web/Pages/SellerPanel/Product/_EditProductVariantPartial.cshtml
@model MarketKhoone.ViewModels.ProductVariants.EditProductVariantViewModel

<div class="row">
    <div class="card text-dark bg-white border-0 shadow">
        <div class="card-body">
            <div class="row">
                <div class="col-md-3 text-center">
                    <img src="~/images/products/@Model.MainPicture" class="w-50" alt="@Model.ProductTitle" />
                </div>
                <div class="col-md-9">
                    <div class="alert alert-secondary">
                        <p class="mb-3 text-center text-primary">
                            <a asp-page="/Product/Index" asp-route-slug="@Model.Slug" asp-route-productCode="@Model.ProductCode" target="_blank">
                                @Model.ProductTitle
                            </a>
                        </p>
                        <div class="row text-center">
                            <div class="col-md-3">
                                دسته بندی:
                                @Model.ProductCategoryTitle
                            </div>
                            <div class="col-md-3">
                                تنوع مجاز این کالا:
                                @{
                                    var variantType = "بدون تنوع";
                                    if (Model.CategoryIsVariantColor != null)
                                    {
                                        variantType = Model.CategoryIsVariantColor.Value ? "رنگ" : "سایز";
                                    }
                                }
                                @variantType
                            </div>
                            <div class="col-md-3">
                                برند کالا:
                                @Model.ProductBrandFullTitle
                            </div>
                            <div class="col-md-3">
                                کمیسیون فروش این کالا:
                                %@Model.CommissionPercentage
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <form functionNameToCallInTheEnd="editProductVariantFunction"
                  method="post" class="public-ajax-form" asp-page-handler="EditProductVariant">
                <input asp-for="Id" />
                <div class="row">
                   @if (Model.IsDiscountActive)
                   {
                       <div class="alert alert-danger">
                           <i class="bi bi-exclamation-triangle-fill rem21px"></i>
                           این محصول دارای تخفیف فعال است، در صورتیکه قیمت را تغییر دهید،
                           تخفیف این تنوع حذف خواهد شد.
                       </div>
                   }
                    <div class="my-2">
                        <label class="form-label" asp-for="Price">
                        </label>
                        <input asp-for="Price" class="form-control" />
                        <span asp-validation-for="Price" class="span-error-message"></span>
                    </div>
                    <div class="my-2">
                        <label class="form-label" asp-for="MaxCountInCart">
                        </label>
                        <input asp-for="MaxCountInCart" class="form-control" />
                        <span asp-validation-for="MaxCountInCart" class="span-error-message"></span>
                    </div>
                </div>
                <div class="d-grid">
                    <input type="submit" class="btn btn-primary" value="ویرایش تنوع" />
                </div>
            </form>
        </div>
    </div>
</div>