src/Marketkhoone.Web/Pages/Admin/FeatureConstantValue/Index.cshtml.cs
using AutoMapper;
using EShopMarket.Common.Helpers;
using MarketKhoone.Common;
using MarketKhoone.Common.Constants;
using MarketKhoone.Common.IdentityToolkit;
using MarketKhoone.DataLayer.Context;
using MarketKhoone.Services.Contracts.IFacadePattern;
using MarketKhoone.ViewModels.FeatureConstantValues;
using Microsoft.AspNetCore.Mvc;

namespace Marketkhoone.Web.Pages.Admin.FeatureConstantValue
{
    public class IndexModel : PageBase
    {
        #region Constructor

        private readonly IFacadeServices _facadeServices;
        private readonly IUnitOfWork _uow;
        private readonly IMapper _mapper;

        public IndexModel(IFacadeServices facadeServices, IUnitOfWork uow, IMapper mapper)
        {
            _facadeServices = facadeServices;
            _uow = uow;
            _mapper = mapper;
        }

        #endregion

        [BindProperty(SupportsGet = true)]
        public ShowFeatureConstantValuesViewModel FeatureConstantValues { get; set; } = new();
        public async Task OnGet()
        {
            var categories = await _facadeServices.CategoryService.GetCategoriesWithNoChild();
            FeatureConstantValues.SearchFeatureConstantValues.Categories =
                categories.CreateSelectListItem(firstItemValue: string.Empty);
        }

        public async Task<IActionResult> OnGetGetDataTableAsync()
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError(string.Empty, PublicConstantStrings.ModelStateErrorMessage);
                return Json(new JsonResultOperation(false, PublicConstantStrings.ModelStateErrorMessage)
                {
                    Data = ModelState.GetModelStateErrors()
                });
            }

            return Partial("List", await _facadeServices.FeatureConstantValueService.GetFeatureConstantValues(FeatureConstantValues));
        }

        public async Task<IActionResult> OnGetGetCategoryFeatures(long categoryId)
        {
            //جرا صفر؟
            // چون موقعی که کاربر خودش میاد و سلکت باکس رو
            //روی انتخاب کنید میزاره
            // مقدار ولیوش صفر میشه و ون آیدی بصورت لانگ غیر نال ایبیل هست، صفر میاد سمت اکشن
            if (categoryId < 0)
            {
                return Json(new JsonResultOperation(false));
            }

            return Json(new JsonResultOperation(true, string.Empty)
            {
                Data = await _facadeServices.CategoryFeatureService.GetCategoryFeatures(categoryId)
            });
        }

        public async Task<IActionResult> OnPostDelete(long featureConstantValueId)
        {
            if (featureConstantValueId < 1)
            {
                return Json(new JsonResultOperation(false));
            }

            var featureConstantValue =
                await _facadeServices.FeatureConstantValueService.FindByIdAsync(featureConstantValueId);

            if (featureConstantValue is null)
            {
                return Json(new JsonResultOperation(false, PublicConstantStrings.RecordNotFoundMessage));
            }

            _facadeServices.FeatureConstantValueService.Remove(featureConstantValue);
            await _uow.SaveChangesAsync();
            return Json(new JsonResultOperation(true, "مقدار ثابت ویژگی مورد نظر با موفقیت حذف شد"));
        }

        public async Task<IActionResult> OnGetAdd()
        {
            //در لودینگ مودال، در همون ابتدا لودینگ
            //یه سلکت باکس داریم که همه دسته بندی ها رو توش پر میکنیم
            // تا کاربر بیاد و انتخاب کنه و....
            var categories = await _facadeServices.CategoryService.GetLastCategoriesWithNoChild();
            var model = new AddFeatureConstantValueViewModel()
            {
                Categories = categories.CreateSelectListItem()
            };
            return Partial("Add", model);
        }

        public async Task<IActionResult> OnPostAdd(AddFeatureConstantValueViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return Json(new JsonResultOperation(false, PublicConstantStrings.ModelStateErrorMessage)
                {
                    Data = ModelState.GetModelStateErrors()
                });
            }
            //آیا مقدار ثابتی که کاربر داره ه ویژگی فلان از فلان دسته بندی میده
            //واقعا متعلق به اون دسته بندی و اون ویژگی هست
            // مثلا رم 16 گیگ رو برای دسته بندی گوشی موبایل باید بفرسته به دسته بندی چادر مسافرتی نفرسته یه موقع

            if (!await _facadeServices.CategoryFeatureService.CheckCategoryFeature(model.CategoryId, model.FeatureId))
            {
                return Json(new JsonResultOperation(false));
            }

            var featureConstantValueToAdd = _mapper.Map<MarketKhoone.Entities.FeatureConstantValue>(model);
            await _facadeServices.FeatureConstantValueService.AddAsync(featureConstantValueToAdd);
            await _uow.SaveChangesAsync();
            return Json(new JsonResultOperation(true, "مقدار ویژگی ثابت مورد نظر یا موفقیت اضافه شد"));
        }

        public async Task<IActionResult> OnGetEdit(long id)
        {
            var featureConstantValue = await _facadeServices.FeatureConstantValueService.FindByIdAsync(id);
            if (featureConstantValue is null)
            {
                return Json(new JsonResultOperation(false, PublicConstantStrings.RecordNotFoundMessage));
            }

            var categories = await _facadeServices.CategoryService.GetCategoriesToShowInSelectBoxAsync();
            var features =
                await _facadeServices.CategoryFeatureService.GetCategoryFeatures(featureConstantValue.CategoryId);

            var model = _mapper.Map<EditFeatureConstantValueViewModel>(featureConstantValue);
            model.Categories = categories.CreateSelectListItem();
            //در اکستنش سلکت لیست آیتمی که ما نوشتیم
            //ویوو مدلی که توسط آن سلکت لیست آیتم پر میشه
            //باید یک 
            //Id, title
            //داشته باشد
            // ولی در ویو مدل این قسمت یعنی 
            //CategoryFeatureForCreateProductViewModel => به متد GetCategoryFeatures نگاه کن که همین ویوو مدل رو گرفته
            //FeatureId, FeatureTitle
            //داریم پس باید به اکستنشن متد بگیم منظور ما از آیدی و تایتل چیه
            model.Features = features.CreateSelectListItem(idPropertyName: "FeatureId", titlePropertyName: "FeatureTitle");
            return Partial("Edit", model);
        }

        public async Task<IActionResult> OnPostEdit(EditFeatureConstantValueViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return Json(new JsonResultOperation(false, PublicConstantStrings.ModelStateErrorMessage)
                {
                    Data = ModelState.GetModelStateErrors()
                });
            }

            if (!await _facadeServices.CategoryFeatureService.CheckCategoryFeature(model.CategoryId, model.FeatureId))
            {
                return Json(new JsonResultOperation(false));
            }

            var featureConstantValue = await _facadeServices.FeatureConstantValueService.FindByIdAsync(model.Id);
            if (featureConstantValue is null)
            {
                return Json(new JsonResultOperation(false, PublicConstantStrings.RecordNotFoundMessage));
            }

            featureConstantValue = _mapper.Map(model, featureConstantValue);
            await _uow.SaveChangesAsync();
            return Json(new JsonResultOperation(true, "مقدار ثابت ویژگی مورد نظر با موفقیت ویرایش شد"));
        }


    }
}

src/Marketkhoone.Web/Pages/Profile/Wallet/Add.cshtml.cs
using AutoMapper;
using MarketKhoone.Common.Constants;
using MarketKhoone.Common.IdentityToolkit;
using MarketKhoone.DataLayer.Context;
using MarketKhoone.Entities.Enums.Order;
using MarketKhoone.Services.Contracts.IFacadePattern;
using MarketKhoone.ViewModels.Wallets;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Parbad;
using Parbad.AspNetCore;
using Parbad.Gateway.ZarinPal;


namespace Marketkhoone.Web.Pages.Profile.Wallet
{
    public class AddModel : PageModel
    {
        #region Constructor

        private readonly IFacadeServices _facadeServices;
        private readonly IMapper _mapper;
        private readonly IOnlinePayment _onlinePayment;
        private readonly IUnitOfWork _uow;

        public AddModel(IFacadeServices facadeServices, IMapper mapper,
            IOnlinePayment onlinePayment, IUnitOfWork uow)
        {
            _facadeServices = facadeServices;
            _mapper = mapper;
            _onlinePayment = onlinePayment;
            _uow = uow;
        }

        #endregion


        [BindProperty]
        public AddValueToWalletViewModel AddValeToWallet { get; set; }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            //کاربر بعد از پرداخت به چه آدرسی باید هدایت شود
            var callBackUrl = Url.PageLink("VerifyPayment", null, null, Request.Scheme);

            var walletToAdd = _mapper.Map<MarketKhoone.Entities.Wallet>(AddValeToWallet);

            walletToAdd.UserId = User.Identity.GetLoggedInUserId();
            walletToAdd.Description = "افزایش موجودی توسط کاربر";

            var result = await _onlinePayment.RequestAsync(invoice =>
            {
                invoice
                    .SetAmount(AddValeToWallet.Value)
                    .SetCallbackUrl(callBackUrl)
                    .SetGateway(AddValeToWallet.PaymentGateway.ToString())
                    .UseAutoIncrementTrackingNumber();
                if (AddValeToWallet.PaymentGateway == PaymentGateway.Zarinpal)
                {
                    invoice.SetZarinPalData(new ZarinPalInvoice("Not description"));
                }
            });

            walletToAdd.TrackingNumber = result.TrackingNumber;

            if (result.IsSucceed)
            {
                await _facadeServices.WalletService.AddAsync(walletToAdd);
                await _uow.SaveChangesAsync();

                return result.GatewayTransporter.TransportToGateway();
            }
            else
            {
                return RedirectToPage(PublicConstantStrings.Error500PageName);
            }
        }
    }
}

src/Marketkhoone.Web/Pages/Admin/FeatureConstantValue/Add.cshtml
@model MarketKhoone.ViewModels.FeatureConstantValues.AddFeatureConstantValueViewModel

<form class="alert alert-secondary custom-ajax-form" asp-page-handler="Add" method="post">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="row">
        <div class="col-12 col-sm-6 col-lg-3 my-2">
            <label class="form-label" asp-for="CategoryId"></label>
            <select class="form-select custom-select2" asp-for="CategoryId" asp-items="Model.Categories">
            </select>
            <span class="span-error-message" asp-validation-for="CategoryId"></span>
        </div>
        <div class="col-12 col-sm-6 col-lg-3 my-2">
            <label class="form-label" asp-for="FeatureId"></label>
            <select class="form-select custom-select2" asp-for="FeatureId">
               @* فیچر آیدی در ویوو مدل بصورت لانگ نال ایبیل هستش
                پس باید یه مقدار رو بهش ست کنید*@
                <option value="0">انتخاب کنید</option>
            </select>
            <span class="span-error-message" asp-validation-for="FeatureId"></span>
        </div>
        <div class="col-12 col-sm-6 col-lg-3 my-2">
            <label class="form-label" asp-for="Value"></label>
            <input class="form-control" asp-for="Value" />
            <span class="span-error-message" asp-validation-for="Value"></span>
        </div>
        <div class="col-12 my-2">
            <div class="d-grid d-lg-block">
                <button type="submit" class="btn btn-primary d-inline-flex align-items-center submit-custom-ajax-button">
                    افزودن
                    <span class="spinner-border spinner-border-sm d-none ms-2"></span>
                </button>
            </div>
        </div>
    </div>
</form>

src/Marketkhoone.Web/Pages/Admin/FeatureConstantValue/Edit.cshtml
@model MarketKhoone.ViewModels.FeatureConstantValues.EditFeatureConstantValueViewModel

<form class="alert alert-secondary custom-ajax-form" asp-page-handler="Edit" method="post">
    <input asp-for="Id" />
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="row">
        <div class="col-12 col-sm-6 col-lg-3 my-2">
            <label class="form-label" asp-for="CategoryId"></label>
            <select class="form-select custom-select2" asp-for="CategoryId" asp-items="Model.Categories">
            </select>
            <span class="span-error-message" asp-validation-for="CategoryId"></span>
        </div>
        <div class="col-12 col-sm-6 col-lg-3 my-2">
            <label class="form-label" asp-for="FeatureId"></label>
            <select class="form-select custom-select2" asp-for="FeatureId" asp-items="Model.Features">
        
            </select>
            <span class="span-error-message" asp-validation-for="FeatureId"></span>
        </div>
        <div class="col-12 col-sm-6 col-lg-3 my-2">
            <label class="form-label" asp-for="Value"></label>
            <input class="form-control" asp-for="Value" />
            <span class="span-error-message" asp-validation-for="Value"></span>
        </div>
        <div class="col-12 my-2">
            <div class="d-grid d-lg-block">
                <button type="submit" class="btn btn-primary d-inline-flex align-items-center submit-custom-ajax-button">
                    ویرایش
                    <span class="spinner-border spinner-border-sm d-none ms-2"></span>
                </button>
            </div>
        </div>
    </div>
</form>

src/Marketkhoone.Web/Pages/Admin/FeatureConstantValue/Index.cshtml
@page
@model Marketkhoone.Web.Pages.Admin.FeatureConstantValue.IndexModel
@{
}

<div class="card text-dark bg-white border-0 shadow">
    <div class="card-body">
        <h5 class="card-title">
            @ViewData["Title"]
        </h5>
        <div class="d-grid d-lg-block mb-2">
            <a asp-page-handler="Add" class="btn btn-outline-primary show-modal-form-button">
                افزودن مقدار ثابت ویژگی
            </a>
        </div>
        <form class="alert alert-secondary search-form-via-ajax">
            <input asp-for="FeatureConstantValues.Pagination.CurrentPage" />
            <input asp-for="FeatureConstantValues.Pagination.PageCount" />
            <div asp-validation-summary="All" class="text-danger"></div>
            <h5>
                جستجو در
                @ViewData["Title"]
            </h5>
            <div class="row">
                <div class="col-12 col-sm-6 col-lg-3 my-2">
                    <label class="form-label" asp-for="FeatureConstantValues.SearchFeatureConstantValues.CategoryId"></label>
                    <select class="custom-select2 form-control" asp-for="FeatureConstantValues.SearchFeatureConstantValues.CategoryId" asp-items="Model.FeatureConstantValues.SearchFeatureConstantValues.Categories"></select>
                    <span class="span-error-message" asp-validation-for="FeatureConstantValues.SearchFeatureConstantValues.CategoryId"></span>
                </div>
                <div class="col-12 col-sm-6 col-lg-3 my-2">
                    <label class="form-label" asp-for="FeatureConstantValues.SearchFeatureConstantValues.FeatureId"></label>
                    <select class="custom-select2 form-control" asp-for="FeatureConstantValues.SearchFeatureConstantValues.FeatureId">
                        <option value="0">انتخاب کنید</option>
                    </select>
                    <span class="span-error-message" asp-validation-for="FeatureConstantValues.SearchFeatureConstantValues.FeatureId"></span>
                </div>
                <div class="col-12 col-sm-6 col-lg-3 my-2">
                    <label class="form-label" asp-for="FeatureConstantValues.SearchFeatureConstantValues.Value"></label>
                    <input class="form-control" asp-for="FeatureConstantValues.SearchFeatureConstantValues.Value" />
                    <span class="span-error-message" asp-validation-for="FeatureConstantValues.SearchFeatureConstantValues.Value"></span>
                </div>
                <div class="col-12 col-sm-6 col-lg-3 my-2">
                    <label class="form-label" asp-for="FeatureConstantValues.SearchFeatureConstantValues.DeletedStatus"></label>
                    <select class="form-select" asp-for="FeatureConstantValues.SearchFeatureConstantValues.DeletedStatus" asp-items="Html.GetEnumSelectList<MarketKhoone.ViewModels.DeletedStatus>()"></select>
                </div>
                <div class="col-12 col-sm-6 col-lg-3 my-2">
                    <label class="form-label" asp-for="FeatureConstantValues.SearchFeatureConstantValues.Sorting"></label>
                    <select class="form-select" asp-for="FeatureConstantValues.SearchFeatureConstantValues.Sorting" asp-items="Html.GetEnumSelectList<MarketKhoone.ViewModels.FeatureConstantValues.SortingBrands>()"></select>
                </div>
                <div class="col-12 col-sm-6 col-lg-3 my-2">
                    <label class="form-label" asp-for="FeatureConstantValues.SearchFeatureConstantValues.SortingOrder"></label>
                    <select class="form-select" asp-for="FeatureConstantValues.SearchFeatureConstantValues.SortingOrder" asp-items="Html.GetEnumSelectList<MarketKhoone.ViewModels.SortingOrder>()"></select>
                </div>
                <div class="col-12 my-2">
                    <div class="d-grid d-lg-block">
                        <button type="submit" class="btn btn-primary d-inline-flex align-items-center search-form-submit-button" disabled>
                            جستجو ...
                            <span class="spinner-border spinner-border-sm d-none ms-2"></span>
                        </button>
                    </div>
                </div>
            </div>
            <div class="data-table-place">
                <div class="text-center data-table-loading">
                    <img src="~/images/application/loading.gif" />
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
    <script src="~/lib/select2/js/select2.min.js"></script>
    <script src="~/lib/select2/js/i18n/fa.min.js"></script>
}
@section CustomScripts{
    <script src="~/Pages/Admin/FeatureConstantValue/Index.cshtml.js"></script>
}
@section Styles{
    <link rel="stylesheet" href="~/lib/select2/css/select2.min.css" />
    <link rel="stylesheet" href="~/lib/select2-bootstrap-5-theme/select2-bootstrap-5-theme.rtl.min.css" />
}

src/Marketkhoone.Web/Pages/Admin/FeatureConstantValue/List.cshtml
@model MarketKhoone.ViewModels.FeatureConstantValues.ShowFeatureConstantValuesViewModel
@if (Model.FeatureConstantValues.Count > 0)
{
    <div class="table-responsive data-table-body">
        <table class="table table-bordered table-striped table-hover">
            <thead class="table-light">
                <tr>
                    <th class="text-center">@Html.DisplayNameFor(x => x.FeatureConstantValues[0].Id)</th>
                    <th class="text-center">@Html.DisplayNameFor(x => x.FeatureConstantValues[0].CategoryTitle)</th>
                    <th class="text-center">@Html.DisplayNameFor(x => x.FeatureConstantValues[0].FeatureTitle)</th>
                    <th class="text-center">@Html.DisplayNameFor(x => x.FeatureConstantValues[0].Value)</th>
                    <th class="text-center">عملیات</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var featureConstantValue in Model.FeatureConstantValues)
                {
                    <tr>
                        <td>@featureConstantValue.Id</td>
                        <td>@featureConstantValue.CategoryTitle</td>
                        <td>@featureConstantValue.FeatureTitle</td>
                        <td>@featureConstantValue.Value</td>
                        <td>
                            <a asp-page-handler="Edit" asp-route-id="@featureConstantValue.Id" class="btn btn-warning show-modal-form-button">
                                ویرایش
                            </a>
                            <form asp-page-handler="Delete" class="d-inline-block">
                                <input type="hidden" name="featureConstantValueId" value="@featureConstantValue.Id" />
                                <button type="button" class="btn btn-danger delete-row-button">حذف</button>
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <!-- Pagination -->
        <div class="btn-toolbar my-3 d-flex justify-content-center" id="main-pagination">
            <div class="btn-group me-2">
                @if (Model.Pagination.CurrentPage != 1)
                {
                    <button value="1" type="button" class="btn btn-outline-primary">
                        <i class="bi bi-chevron-double-right"></i>
                    </button>
                    <button value="@(Model.Pagination.CurrentPage - 1)" type="button" class="btn btn-outline-primary">قبلی</button>
                }
                @for (int counter = Model.Pagination.StartPage; counter <= Model.Pagination.EndPage; counter++)
                {
                    <button value="@counter" type="button"
                            class="@(counter == Model.Pagination.CurrentPage ? "active " : string.Empty)btn btn-outline-primary">
                        @counter
                    </button>
                }
                @if (Model.Pagination.CurrentPage != Model.Pagination.PagesCount)
                {
                    <button value="@(Model.Pagination.CurrentPage + 1)" type="button" class="btn btn-outline-primary">بعدی</button>
                    <button data-bs-toggle="tooltip" data-bs-placement="top" title="کل صفحات @Model.Pagination.PagesCount" value="@Model.Pagination.PagesCount" type="button" class="btn btn-outline-primary">
                        <i class="bi bi-chevron-double-left"></i>
                        @Model.Pagination.PagesCount
                    </button>
                }
            </div>
            <div>
                <select id="page-count-selectbox" asp-for="Pagination.PageCount" class="form-select" asp-items="Html.GetEnumSelectList<MarketKhoone.ViewModels.PageCount>()"></select>
            </div>
        </div>
        <div class="col-10 col-sm-6 col-md-4 col-xl-3 m-auto">
            <div class="input-group">
                <input id="page-number-input" value="@Model.Pagination.CurrentPage" min="1" max="@Model.Pagination.PagesCount" type="number" class="form-control rtl-direction" placeholder="شماره صفحه">
                <button id="go-to-page-button" class="btn btn-outline-primary" type="submit">برو به صفحه</button>
            </div>
        </div>
        <!-- End pagination -->
    </div>
}
else
{
    <partial name="_RecordNotFound" />
}